# Generated by Django 5.1.4 on 2024-12-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
